# Site settings
title: Geoff Thierman • design • code
email: gthierman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web designer and developer based in Vancouver, Canada
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gthierman.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title
defaults:
  - scope:
      path: "images"
    values:
      image: true

sass:
  load_paths:
    - css/_scss
    - node_modules
